### ISSUE TITLE
use Username and Password in cdr_mysql.conf

### ISSUE THREAD

**Issue by mibcadet** [minoruta/ast_mongo#1]
Hi,

is it possible to give also authentication credentials to cdr_mongo.conf file?

Kind regards!
Pawel

**Comment by minoruta** [comment]
Yes,
you can specify your authentication into cdr_mongo.conf.
- For example;
  
  ```
  mongo> use cdr
  mongo> db.createUser(
  mongo>   {
  mongo>     user: "myTester",
  mongo>     pwd: "xyz123",
  mongo>     roles: [
  mongo>       { role: "readWrite", db: "cdr" }
  mongo>     ]
  mongo>   }
  mongo> )
  ```
- cdr_mongodb.conf
  
  ```
  [mongodb]
  uri=mongodb://myTester:xyz123@mongodb.local/cdr
  database=cdr
  collection=cdr
  ```
- see also
  - [Connection String URI Format](https://docs.mongodb.com/manual/reference/connection-string/)

Regards,
minoruta

**Comment by mibcadet** [comment]
Awesome, thanks for quick replay!!!

What I was missing: "uri=mongodb://myTester:xyz123@mongodb.local/cdr"
I thought in cdr_mongodb.conf will be variables like username and password, but that's even better! :)
