### ISSUE TITLE
I am getting "HTTP 401" error when i try to put pjsip to asterisk

### ISSUE THREAD

**Issue by cwizcagdas** [minoruta/ast_mongo#10]
Im trying to put pjsips to mongo via asterisk.I build an asterisk with mongodb and it seems fine. I get to mongo cli and when i launch asterisk cli it says connected but when i try to put pjsip to asterisk via http request i get http 401 error. I am using 'http://0.0.0.0:8088/ari/asterisk/config/dynamic/res_pjsip/ ....'  url in http request to asterisk. Url in asterisk confs is mongodb://127.0.0.1:27017 and i configured others as you presented. Could you please help me with this issue? Im willing to give you additional information

**Comment by minoruta** [comment]
@cwizcagdas
Sorry, I couldn't understand what you're doing due to less information.

**Comment by cwizcagdas** [comment]
I am coding mean stack app and using asterisk ari to push pjsips. I need use mongodb instead of onboard mysql in asterisk so i need ast_mongo to work. I have coded a js to push pjsips to asterisk and write them on onboard mysql. I am trying to do exact thing but instead of mysql, i need to write it on mongo db. Asterisk and mongodb seems connected right now. I am using 'http://0.0.0.0:8088/ari/asterisk/config/dynamic/res_pjsip/' url in my js to push my request to asterisk and uri of mongodb in asterisk configuration files is mongodb://127.0.0.1:27017. What kind of approach should i take ? Thank you

**Comment by minoruta** [comment]
@cwizcagdas
OK,
I understood you mentioned about 'ARI Push Configuration'.
It however is not implemented yet.

You have to use MongoDB directly to add, update and delete PJSIP resources.
[This](https://github.com/minoruta/ast_mongo/blob/master/test_bench/tester/nodejs/testlib/mongo.js) is a simple example how to manipulate it.

On the other hands, I may add such interface to next update.

**Comment by minoruta** [comment]
Any update or I'll close this issue.

Thanks

**Comment by minoruta** [comment]
I close this issue,
thanks.
