### ISSUE TITLE
Realtime Queue Log is not storing

### ISSUE THREAD

**Issue by isravelraja** [minoruta/ast_mongo#11]
Minrouta,

Thanks for the awesome tool you created, 

I am facing issue with realtime queue_log. Its not storing any logs whenever call landed in queue,
Here is my extconfig 
queue_log => mongodb,asterisk

res_config_mongodb.conf
[mongodb]
uri=mongodb://admin:password@127.0.0.1:27017

asterisk cli log:

[Dec  6 21:56:41] DEBUG[9462][C-00000000]: res_config_mongodb.c:815 require: required model is "{ "data1" : 2, "data2" : 2, "data3" : 2, "data4" : 2, "data5" : 2 }"
[Dec  6 21:56:41] DEBUG[9462][C-00000000]: res_config_mongodb.c:361 model_register: queue_log already registered
[Dec  6 21:56:41] DEBUG[9462][C-00000000]: res_config_mongodb.c:858 store: database=asterisk, table=queue_log

when i checked on the mongodb database, there is no data. Can you find anything wrong with this one. 

Thank you again for this amazing tool

**Comment by minoruta** [comment]
@isravelraja

Bad news:
The current ast_mongo has no function for queue log.

Good news:
The queuelog was not included in one of the aims of this project,
but the latest code I have makes `{ "_id" : ObjectId, "time" : "2017-12-07...", "event" : "QUEUESTART", "agent" : "NONE", "queuename" : "NONE", "callid" : "NONE" }` with `queue_log => mongodb,asterisk,queue_log @ extconfig.conf`.

I'd like to release the code in this month.

**Comment by isravelraja** [comment]
Thanks for the reply minoruta. So you going to make different
res_config_mongodb.c for the queue or making new module.



On 08-Dec-2017 3:21 AM, "minoruta" <notifications@github.com> wrote:

@isravelraja <https://github.com/isravelraja>

Bad news:
The current ast_mongo has no function for queue log.

Good news:
The queuelog was not included in one of the aims of this project,
but the latest code I have makes { "_id" : ObjectId, "time" :
"2017-12-07...", "event" : "QUEUESTART", "agent" : "NONE", "queuename" :
"NONE", "callid" : "NONE" } with queue_log => mongodb,asterisk,queue_log @
extconfig.conf.

I'd like to release the code in this month.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/minoruta/ast_mongo/issues/11#issuecomment-350067764>,
or mute the thread

**Comment by isravelraja** [comment]
Also please let me know once you done releasing the new version.

**Comment by isravelraja** [comment]
Minrouta,

Did you add queue_log in ast_mongo by anychance?

**Comment by minoruta** [comment]
@isravelraja 
The latest code of the [branch v0.3](https://github.com/minoruta/ast_mongo/tree/v0.3) might be the code, but I haven't done testing it.

**Comment by isravelraja** [comment]
I had tested with that, It gives me the same old debug log

[Jan  4 19:37:08] DEBUG[19704][C-00000001]: res_config_mongodb.c:815 require: required model is "{ "data1" : 2, "data2" : 2, "data3" : 2, "data4" : 2, "data5" : 2 }"
[Jan  4 19:37:08] DEBUG[19704][C-00000001]: res_config_mongodb.c:366 model_register: models is "{ "queue_log" : { "data1" : 2, "data2" : 2, "data3" : 2, "data4" : 2, "data5" : 2 } }"
[Jan  4 19:37:08] DEBUG[19704][C-00000001]: res_config_mongodb.c:858 store: database=asterisk, table=queue_log
[Jan  4 19:37:13] DEBUG[19704][C-00000001]: res_config_mongodb.c:815 require: required model is "{ "data1" : 2, "data2" : 2, "data3" : 2, "data4" : 2, "data5" : 2 }"
[Jan  4 19:37:13] DEBUG[19704][C-00000001]: res_config_mongodb.c:361 model_register: queue_log already registered
[Jan  4 19:37:13] DEBUG[19704][C-00000001]: res_config_mongodb.c:858 store: database=asterisk, table=queue_log

**Comment by minoruta** [comment]
Thanks for your info.
It's correct.
They are just debug logs, not errors nor even warnings.
How about records on mongodb?
There's still no records?

**Comment by isravelraja** [comment]
Yes, there are no records pushing to Queue log document in MongoDB. but for CDR its pushing without an issue.

**Comment by minoruta** [comment]
Thanks, again. 
Did you confirm with the latest code which is branch v0.3 ? 
The logs are completely same as one you mentioned before. 
The line number of the logs must be different at least.
You are using ~~same~~ old code.

**Comment by isravelraja** [comment]
Yes, i did try with V0.3 https://github.com/minoruta/ast_mongo/tree/v0.3 only.

**Comment by minoruta** [comment]
Any update or I'll close this issue.

Thanks

**Comment by isravelraja** [comment]
Did you made the changes on code. Is it updating the queue logs.

**Comment by minoruta** [comment]
As I mentioned above, the queues logging is already available.

You can check the availability as follows;

1. add a following line into bottom of `extconfig.conf`;
```
queue_log => mongodb,[db name],[collection name]
ex: queue_log => mongodb,queues,queues
```  
2. execute a test in order to do some operations with astersik;
```
ex: # npm test
```
3. confirm the results;
```
# mongo
> use queues
> db.queues.find()
{ "_id" : ObjectId("5be0dbed86efc3000827e3c9"), "time" : "2018-11-06 00:10:21.009417", "event" : "CONFIGRELOAD", "agent" : "NONE", "queuename" : "NONE", "callid" : "NONE" }
```

I'm sorry for my less information.
Regards.

**Comment by isravelraja** [comment]
Thank you. Please close the ticket.

**Comment by minoruta** [comment]
Thanks, isravelraja.
I added some descriptions about queue logging; 00d6360074ef5c1569f545f7d40703cca0b6d268 .
