### ISSUE TITLE
Realtime Extensions

### ISSUE THREAD

**Issue by warpunish** [minoruta/ast_mongo#12]
Hi,
How can we use realtime extensions like endpoints or auths ?

**Comment by minoruta** [comment]
@warpunish

[res_config_mongodb-test.js](https://github.com/minoruta/ast_mongo/blob/master/test_bench/tester/nodejs/res_config_mongodb-test.js) is one of examples.

You can configure such endpoints and auths through mongodb.

**Comment by warpunish** [comment]
I didn't ask for realtime endpoints. I meant realtime extension.conf just like endpoints being realtime.

**Comment by minoruta** [comment]
OK, see [ast_mongo_data.mongo](https://github.com/minoruta/ast_mongo/blob/master/test_bench/scripts/ast_mongo_data.mongo) as an offline example.

For an online example is;
1. store static configs data via e.g. mongoose.js,
1. execute `'dialplan reload'`  via e.g. AMI to reload such extensions.

**Comment by minoruta** [comment]
Any update or I'll close this issue.

Thanks

**Comment by minoruta** [comment]
I close this issue,
thanks.
