### ISSUE TITLE
Installing without Docker 

### ISSUE THREAD

**Issue by GuilhermeCanal** [minoruta/ast_mongo#21]
Hello, first of all great work on this plugin, minoruta,. It's very difficult to find something between Asterisk and Mongodb.
Secondly, I'm having trouble trying to install this plugin, I tryied many different ways, running .patch, compiling the .c and manually loading them to asterisk's modules, but had no success. 
With the updates in the code I think some files went missing and it's difficult to understand how we must setup some .conf files, could you help? (I'm in a Debian 9 environment)

**Comment by minoruta** [comment]
OK, you ask me multiple questions.

#Q1 Can you make new issue for it?

#Q2 You can get some info. from the [old test bench](https://github.com/minoruta/ast_mongo/tree/v0.2/test_bench) in [v0.2](https://github.com/minoruta/ast_mongo/tree/v0.2).
The [test script](https://github.com/minoruta/ast_mongo/blob/v0.2/test_bench/scripts/provisioning.sh) is written for Ubuntu platform.

**Comment by GuilhermeCanal** [comment]
Hello, I think #Q1 will be answered together with #Q2. I tried to install using the script you answered with asterisk version 15.0.0, pjproject 2.7 and mongo-c-driver 1.8.2. The installation went perfectly but the folder "$MOUNT_POINT/src" and "$MOUNT_POINT/configs" didn't exist and the modules are not being installed.
But "$MOUNT_POINT/patches" does exist.

**Comment by minoruta** [comment]
You can use;
 [ast_mongo/patches/ast_mongo-15.3.0.patch](https://github.com/minoruta/ast_mongo/blob/master/patches/ast_mongo-15.3.0.patch) or
 [ast_mongo/patches/ast_mongo-15.4.0.patch](https://github.com/minoruta/ast_mongo/blob/master/patches/ast_mongo-15.4.0.patch),
but you don't always need such patches.

See following section of the test script in detail;
```
        cd $HOME/asterisk-$VERSION_ASTERISK/cdr
        cp $MOUNT_POINT/src/cdr_mongodb.c .
        git add .
        cd $HOME/asterisk-$VERSION_ASTERISK/cel
        cp $MOUNT_POINT/src/cel_mongodb.c .
        git add .
        cd $HOME/asterisk-$VERSION_ASTERISK/res
        cp $MOUNT_POINT/src/res_mongodb.c .
        cp $MOUNT_POINT/src/res_mongodb.exports.in .
        cp $MOUNT_POINT/src/res_config_mongodb.c .
        git add .
        cd $HOME/asterisk-$VERSION_ASTERISK/include/asterisk
        cp $MOUNT_POINT/src/res_mongodb.h .
        git add .
        cd $HOME/asterisk-$VERSION_ASTERISK
        ##  patch for configure.ac makeopts.in build_tools/menuselect-deps.in
        ##  which was generated with 'git diff configure.ac makeopts.in build_tools/menuselect-deps.in'
        patch -p1 -F3 -i $MOUNT_POINT/src/mongodb.for.asterisk.patch
```
which just copied some files from src.

You have two choices above.

**Comment by GuilhermeCanal** [comment]
Hello, I tried to install following your last comment but had no success yet, while copying the files from src I had no issues, but when I was in "make menuselect" in asterisk I noticed the mongo plugins were with a XXX in their select, see it here [screenshot1](http://prntscr.com/leps3g) .
I finished the asterisk's installation, had no apparently errors, but then my /etc/asterisk/ folder had some files pointing to an nonexistent folder: /mnt/configs/
I tried to install with Asterisk 15.4.0 and 15.0.0, but both had the exactly same results

**Comment by minoruta** [comment]
The mongo-c-driver lib might be not installed properly.

You can check the availability with following command;
```
# pkg-config --libs libmongoc-1.0
-L/usr/local/lib -lmongoc-1.0 -lsasl2 -lssl -lcrypto -lrt -lresolv -lz -lbson-1.0
```
or
```
# after execution of ./configure ...
# grep -i mongoc config.log 
configure:30805: checking for mongoc_init in -lmongoc-1.0
configure:30830: gcc -o conftest -g -O2 -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0   conftest.c -lmongoc-1.0   -lm  >&5
configure:30862: checking libmongoc-1.0/mongoc.h usability
configure:30862: gcc -c -g -O2   -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0 conftest.c >&5
configure:30862: checking libmongoc-1.0/mongoc.h presence
configure:30862: gcc -E   -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0 conftest.c
configure:30862: checking for libmongoc-1.0/mongoc.h
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
| #define HAVE_MONGOC 1
ac_cv_header_libmongoc_1_0_mongoc_h=yes
ac_cv_lib_mongoc_1_0_mongoc_init=yes
MONGOC_DIR=''
MONGOC_INCLUDE=' -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0'
MONGOC_LIB=' -lmongoc-1.0 '
PBX_MONGOC='1'
#define HAVE_MONGOC 1
```

**Comment by GuilhermeCanal** [comment]
It worked! By doing the grep -i mongoc config.log  I noticed that error:

`/usr/include/libmongoc-1.0/mongoc.h:22:18: fatal error: bson.h: No such file or directory
| #include <libmongoc-1.0/mongoc.h>`

I searched my files and versions of my libs and some of them (libbson, cmake, etc) were outdated (I was installing them via apt-get), so I installed all the libs via tarball, then used the patch like in your older comment, configured asterisk and mongo and it is working perfectly now (even in version 16.0 of asterisk).
Thank you very much Sir!
