### ISSUE TITLE
I encountered some errors and warnings

### ISSUE THREAD

**Issue by duccomcoltd** [minoruta/ast_mongo#23]
![error_1](https://user-images.githubusercontent.com/28948516/48493168-f4b67180-e85d-11e8-9fdd-3cf4447041f3.png)
![error_2](https://user-images.githubusercontent.com/28948516/48493170-f4b67180-e85d-11e8-8be5-fbc6d3997680.png)
Can you explain why and help me debug. Thank!
I've used:
- CentOS-6.9 x64
- Asterisk 13.x and Asterisk 16.0.0 (have the same problem)

**Comment by minoruta** [comment]
You have to specify /etc/asterisk/[ast_mongo.conf](https://github.com/minoruta/ast_mongo/blob/master/test_bench/configs/ast_mongo.conf) properly.

It means that there are no [config] and [cel] sections.

**Comment by duccomcoltd** [comment]
Thank you very much, you are wonderful.
I've seen detailed call history in mongodb
![ast_mongo](https://user-images.githubusercontent.com/28948516/48554212-5cc59000-e910-11e8-9657-690e357e341c.png)
